import Delete from './builder/operations/Delete';
import Get from './builder/operations/Get';
import Put from './builder/operations/Put';
import Query from './builder/operations/Query';
import Scan from './builder/operations/Scan';
import Update from './builder/operations/Update';
export declare const ConstructGet: typeof Get;
export declare const ConstructDelete: typeof Delete;
export declare const ConstructPut: typeof Put;
export declare const ConstructQuery: typeof Query;
export declare const ConstructScan: typeof Scan;
export declare const ConstructUpdate: typeof Update;
export { getAllPages } from './utils';
export { BuilderType } from './builder';
